version: '3.8'

services:
  app:
    build: .
    container_name: my_go_service
    restart: always
    depends_on:
      - db
    environment:
      DB_DSN: postgres://admin:password@db:5432/car?sslmode=disable
      LISTEN: 8080
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: admin
      DB_PASSWORD: password
      DB_NAME: car
    ports:
      - "8080:8080"
    networks:
      - backend

  db:
    image: postgres:15
    container_name: my_postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: car
    ports:
      - "5555:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend

networks:
  backend:

volumes:
  pgdata:
